### ISSUE TITLE
Not creating the right merchantParameters

### ISSUE THREAD

**Issue by lluisandreu** [boyander/redsys-polite#3]
Hello, 

Maybe some of you can help me with this. I am having an issue with this package and all NPM packages I have tried. When submitting the form I always get "Error en datos enviados. Contacte con su comercio. Importe 0 Sin Asignar " because merchantParameters and signature are not right. 

Using the same FUC and SECRET in a PHP environment using Redsys API PHP doesn't give me any problem at all.

This is my code

```
const order = new Date().getTime().toString();
                const total = parseInt(this.getTotal) * 100;

                const redsys = new RedsysBuilder()
                    .setMerchantCode(process.env.VUE_APP_REDSYS_FUC)
                    .setName(process.env.VUE_APP_NAME)
                    .setTitular(process.env.VUE_APP_NAME)
                    .setSecret(process.env.VUE_APP_REDSYS_SECRET)
                    .enableDebug()
                    .build();

                const payment = new PaymentBuilder()
                    .setTotal(this.getTotal)
                    .setOrderId("1")
                    .setUrlMerchant(process.env.VUE_APP_URL)
                    .setUrlCancel(process.env.VUE_APP_URL + 'pagament/ko')
                    .setUrlOK(process.env.VUE_APP_URL + 'pagament/ok')
                    .build();

                const form_encoded_params = redsys.getFormData(payment);
```

Thanks in advance.

**Comment by sergiojup** [comment]
Hello.

I see that you are sending the amount * 100 and this could be the problem.
When you call PaymentBuilder(), the .setTotal() function is already doing this (multiplying amount * 100). Take a look at "src/payment.js" setTotal() function.

So, I think you have to send the normal price. In my code I usually send parseFloat(price).

Hope this helps.

Regards

**Comment by boyander** [comment]
Many thanks! would you mind doing a PR?
